## ----------------------------------------------------------------------------
## nexus | SingleParticle.mac
##
## Ancillary macro to define the parameters of the single particle generator.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 3.5425 eV
/Generator/SingleParticle/max_energy 3.7571 eV
/Generator/SingleParticle/min_costheta -1
/Generator/SingleParticle/max_costheta +1
/Generator/SingleParticle/min_phi   0.0
/Generator/SingleParticle/max_phi   6.2831
#/Generator/SingleParticle/min_energy 2.8 eV
#/Generator/SingleParticle/max_energy 2.82 eV
#/Generator/SingleParticle/min_costheta 0.5
#/Generator/SingleParticle/max_costheta 0.6
#/Generator/SingleParticle/min_phi   4.7123
#/Generator/SingleParticle/max_phi   4.7123

/Generator/SingleParticle/region whatever