## ----------------------------------------------------------------------------
## nexus | SingleParticle.mac
##
## Ancillary macro to define the parameters of the single particle generator.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy 3. eV
/Generator/SingleParticle/max_energy 3.6 eV
/Generator/SingleParticle/min_costheta 0.
/Generator/SingleParticle/max_costheta 0.
/Generator/SingleParticle/min_phi   4.7123
/Generator/SingleParticle/max_phi   4.7123
/Generator/SingleParticle/region whatever