/control/execute macros/physics/OpticalPhysics.mac

/nexus/RegisterGeometry DichroicTest

/nexus/RegisterGenerator SingleParticleGenerator
#/nexus/RegisterGenerator LArScintillationGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterTrackingAction OpticalTrackingAction

/nexus/RegisterMacro macros/DichroicTest.config.mac