/control/execute macros/physics/OpticalPhysics.mac

/nexus/RegisterGeometry DimpleTest

/nexus/RegisterGenerator PTPPhotonGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
#/nexus/RegisterSteppingAction SaveAllSteppingAction
/nexus/RegisterTrackingAction OpticalTrackingAction

/nexus/RegisterMacro macros/DimpleTest.config.mac