/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

#---- Parameters used for every configuration ----#
/Geometry/XArapuca/config_code                          1
/Geometry/XArapuca/surrounding_media                    lar
/Geometry/XArapuca/internal_length                      613     mm 
/Geometry/XArapuca/internal_width                       613     mm
# Update the following value accordingly to 
# plate_thickn: it should be plate_thickn +12.2 mm
/Geometry/XArapuca/internal_thickn                      16. mm
/Geometry/XArapuca/DFA_thickn                           6.35    mm
/Geometry/XArapuca/DF_thickn                            1.50    mm
/Geometry/XArapuca/DF_substrate_thickn                  1.49    mm
/Geometry/XArapuca/DF_substrate_mpt                     SCHOTT_BOROFLOAT_33
/Geometry/XArapuca/DF_pos_wrt_DFA_pos                   0. 
/Geometry/XArapuca/DF_are_coated                        true
/Geometry/XArapuca/coating_thickn                       3.226   um
/Geometry/XArapuca/coating_rindex                       1.65
/Geometry/XArapuca/outter_frame_width_along_wlsplength  33.9    mm
/Geometry/XArapuca/outter_frame_width_along_wlspwidth   33.9    mm
/Geometry/XArapuca/inner_frames_width_along_wlsplength  4.      mm
/Geometry/XArapuca/inner_frames_width_along_wlspwidth   4.      mm
/Geometry/XArapuca/df_no_along_wlsplength               4 
/Geometry/XArapuca/df_no_along_wlspwidth                4
/Geometry/XArapuca/DFA_config_code                      1
/Geometry/XArapuca/DFA_frame_is_reflective              false
/Geometry/XArapuca/vikuiti_reflectivity_scale_factor    1.
/Geometry/XArapuca/DFA_frame_is_specular                false
/Geometry/XArapuca/remove_DFs                           false
/Geometry/XArapuca/remove_DFA_frame                     false
/Geometry/XArapuca/secondary_wls_attlength              1.5     m
/Geometry/XArapuca/cromophore_concentration             80.0
/Geometry/XArapuca/cryogenic_temperature                true
# The following value is set to make the DFs be 143.75 mm
# x 143.75 mm given that the internal_length is set to 613
/Geometry/XArapuca/case_thickn                          20.9    mm
/Geometry/XArapuca/SiPM_code                            2
/Geometry/XArapuca/PS_config_code                       1
/Geometry/XArapuca/num_phsensors                        40
/Geometry/XArapuca/gap                                  0.05   mm
/Geometry/XArapuca/ref_phsensors_supports               false
/Geometry/XArapuca/double_sided                         true
/Geometry/XArapuca/collectors_are_reflective            true
/Geometry/XArapuca/generation_region                    dichroic
/Geometry/XArapuca/gen_x                                0.     cm
/Geometry/XArapuca/gen_z                                0.     cm
/Geometry/XArapuca/gen_diameter                         2.    cm
#/Geometry/XArapuca/path_to_inwards_dichroic_data        data/filters_data/opto/ific_meas/g4_dichroic_data_from_SCHOTTB270
#/Geometry/XArapuca/path_to_outwards_dichroic_data       data/filters_data/opto/ific_meas/g4_dichroic_data_from_SCHOTTB270
/Geometry/XArapuca/path_to_inwards_dichroic_data        data/filters_data/photonexport/15x15v1/ific/g4_dichroic_data_from_quartz
/Geometry/XArapuca/path_to_outwards_dichroic_data       data/filters_data/photonexport/15x15v1/ific/g4_dichroic_data_from_quartz
#/Geometry/XArapuca/path_to_inwards_dichroic_data        data/filters_data/photonexport/tentative_fourth_batch/definitive/shifted_g4like_transmitance_files/CP700.0
#/Geometry/XArapuca/path_to_outwards_dichroic_data       data/filters_data/photonexport/tentative_fourth_batch/definitive/shifted_g4like_transmitance_files/CP700.0
#                                                       CHECK THAT YOU ARE SETTING THE MPT FOR THE SUBSTRATE MPT IN THE .CC FILE! THIS CANNOT BE SET VIA MACRO YET!

#---- config_code_==1 parameters ----#
/Geometry/XArapuca/plate_length                         605. mm
/Geometry/XArapuca/plate_width                          605. mm
/Geometry/XArapuca/plate_thickn                         3.8 mm
/Geometry/XArapuca/tunneling_probability                0.01
/Geometry/XArapuca/sipms_at_x_plus                      true
/Geometry/XArapuca/sipms_at_x_minus                     true
/Geometry/XArapuca/sipms_at_z_plus                      true
/Geometry/XArapuca/sipms_at_z_minus                     true
/Geometry/XArapuca/with_boards                          true
/Geometry/XArapuca/add_blocks_between_sipms             false
/Geometry/XArapuca/with_dimples                         false
/Geometry/XArapuca/dimple_type                          flat
/Geometry/XArapuca/flat_dimple_width                    8.      mm
/Geometry/XArapuca/flat_dimple_depth                    1.2     mm
/Geometry/XArapuca/curvy_dimple_radius                  4.0 mm
/Geometry/XArapuca/cut_plate                            false
/Geometry/XArapuca/cut_angle                            0.69813170079   # 40 º, in radians
/Geometry/XArapuca/cut_thickness                        1.      mm
/Geometry/XArapuca/place_foil_at_the_cut                false       

#---- config_code_==2 parameters ----#
/Geometry/XArapuca/fibers_number                        20
/Geometry/XArapuca/fiber_planes                         1
/Geometry/XArapuca/fiber_radius                         3.      mm
/Geometry/XArapuca/fiber_length                         236.    mm
/Geometry/XArapuca/along_long_side                      true

/control/execute macros/generators/LArScintillationGeneratorY.mac

/nexus/persistency/output_file output/TrashCan
    
#With a 1.2 mm deep flat dimple, and a 1.5 mm thick sipm, this is the better we can do to approach
#approach the 2 mm board-plate distance without setting an actual optical contact between the sipm and the plate.
#Typical gap for immersion of sipms within cylindrical dimples with r=4.0mm is -1.4*mm
#Old supercells unique DF transverse dimensions  (487. mm x 93. mm)
#Frame width to match 97mmx97mm DFs: 2.85 mm