/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

#---- Parameters used for every configuration ----#

/Geometry/XArapucaRods/surrounding_media                    lar
/Geometry/XArapucaRods/DFA_thickn                           6.      mm
/Geometry/XArapucaRods/DF_thickn                            1.01    mm
/Geometry/XArapucaRods/DF_substrate_thickn                  1.      mm
/Geometry/XArapucaRods/DF_pos_wrt_DFA_pos                   0. 
/Geometry/XArapucaRods/DF_are_coated                        true
/Geometry/XArapucaRods/coating_thickn                       3.226   um
/Geometry/XArapucaRods/coating_rindex                       1.65
/Geometry/XArapucaRods/outter_frame_width_along_wlsplength  10.     mm
/Geometry/XArapucaRods/outter_frame_width_along_wlspwidth   10.     mm
/Geometry/XArapucaRods/inner_frames_width_along_wlsplength  4.      mm
/Geometry/XArapucaRods/inner_frames_width_along_wlspwidth   4.      mm
/Geometry/XArapucaRods/df_no_along_wlsplength               6 
/Geometry/XArapucaRods/df_no_along_wlspwidth                1
/Geometry/XArapucaRods/DFA_config_code                      1
/Geometry/XArapucaRods/DFA_frame_is_reflective              false
/Geometry/XArapucaRods/DFA_frame_is_specular                false
/Geometry/XArapucaRods/remove_DFs                           true
/Geometry/XArapucaRods/remove_DFA_frame                     true
/Geometry/XArapucaRods/secondary_wls_attlength              1.5     m
/Geometry/XArapucaRods/cromophore_concentration             24.
/Geometry/XArapucaRods/case_thickn                          1.      mm
/Geometry/XArapucaRods/SiPM_code                            2
/Geometry/XArapucaRods/num_phsensors                        15
/Geometry/XArapucaRods/rod_sipm_gap                         0.1     mm
/Geometry/XArapucaRods/ref_phsensors_supports               true
/Geometry/XArapucaRods/double_sided                         true
/Geometry/XArapucaRods/generation_region                    dichroic
/Geometry/XArapucaRods/gen_x                                0.     cm
/Geometry/XArapucaRods/gen_z                                0.     cm
/Geometry/XArapucaRods/gen_diameter                         2.    cm
#/Geometry/XArapucaRods/path_to_inwards_dichroic_data        data/filters_data/opto/ific_meas/g4_dichroic_data_from_SCHOTTB270
#/Geometry/XArapucaRods/path_to_outwards_dichroic_data       data/filters_data/opto/ific_meas/g4_dichroic_data_from_SCHOTTB270
/Geometry/XArapucaRods/path_to_inwards_dichroic_data        data/filters_data/photonexport/15x15v1/ific/g4_dichroic_data_from_quartz
/Geometry/XArapucaRods/path_to_outwards_dichroic_data       data/filters_data/photonexport/15x15v1/ific/g4_dichroic_data_from_quartz
#/Geometry/XArapucaRods/path_to_inwards_dichroic_data        data/filters_data/photonexport/tentative_fourth_batch/definitive/shifted_g4like_transmitance_files/CP700.0
#/Geometry/XArapucaRods/path_to_outwards_dichroic_data       data/filters_data/photonexport/tentative_fourth_batch/definitive/shifted_g4like_transmitance_files/CP700.0
#                                                       CHECK THAT YOU ARE SETTING THE MPT FOR THE SUBSTRATE MPT IN THE .CC FILE! THIS CANNOT BE SET VIA MACRO YET!
/Geometry/XArapucaRods/tunneling_probability                0.01
/Geometry/XArapucaRods/add_blocks_between_sipms             false
/Geometry/XArapucaRods/rod_length                           500.    mm
/Geometry/XArapucaRods/rod_height                           6.4     mm
/Geometry/XArapucaRods/rod_width                            96     mm
/Geometry/XArapucaRods/rods_no                              1
/Geometry/XArapucaRods/add_reflective_separators            true
/Geometry/XArapucaRods/rods_lateral_gap                     0.1     mm
/Geometry/XArapucaRods/along_long_side                      true        # SPURIOUS ??
/Geometry/XArapucaRods/cut_rods                             true
#/Geometry/XArapucaRods/cut_angle                            1.483529864   # 85 º, in radians
#/Geometry/XArapucaRods/cut_angle                            1.308996939   # 75 º, in radians
/Geometry/XArapucaRods/cut_angle                            0.69813170079   # 40 º, in radians
/Geometry/XArapucaRods/cut_thickness                        1.      mm
/Geometry/XArapucaRods/place_separator_at_the_cut           true

/control/execute macros/generators/LArScintillationGeneratorY.mac
#/control/execute macros/generators/SingleParticleRodsModule.mac

/nexus/persistency/output_file output/FakeSupercell
    
#With a 1.2 mm deep flat dimple, and a 1.5 mm thick sipm, this is the better we can do to approach
#approach the 2 mm board-plate distance without setting an actual optical contact between the sipm and the plate.
#Typical gap for immersion of sipms within cylindrical dimples with r=4.0mm is -1.4*mm
#Old supercells unique DF transverse dimensions  (487. mm x 93. mm)
#Frame width to match 97mmx97mm DFs: 2.85 mm